### ISSUE TITLE
Bluetooth...

### ISSUE THREAD

**Issue by pearson** [Ayehavgunne/pypad#2]
I'm curious... Is there room inside the shell for batteries, perhaps like an 18650? With a battery and by replacing the Teensy with something like an nRF52840 (used for many wireless Bluetooth devices), a wireless Tartarus with a long battery life could be possible. 😃 (While MicroPython is available, I don't know how well it supports the nRF52840's low power modes, though. Those modes would be a must when battery powered.) Personally, I'd love to get rid of the cable to make it easier to move the Tartarus out of the way.

Amazing work on this project, BTW!

**Comment by Ayehavgunne** [comment]
I'm pretty sure there is room for batteries. It would just be a matter of cutting away more material inside to make space.

**Comment by pearson** [comment]
Okay, that is definitely interesting. Thanks for the info! I'll probably have a look at it pretty soon -- my thumbstick is wearing out. :unamused:
